### ISSUE TITLE
Home button not working

### ISSUE THREAD

**Issue by skepzz** [FlymeDllVa/iCloud-Bypass-via-USB#1]
After running the script and everything completing successfully. I can now not use my home button on the welcome screen to even try to activate it. please advise

**Comment by skepzz** [comment]
acbooks-MacBook-Air:iOSRestrictionBruteForce macair$ python3 /Users/macair/Downloads/iOSRestrictionBruteForce/iCloud-Bypass-via-USB/bypass.py 
Forwarding local port 2222 to remote port 44
Incoming connection to 2222
Waiting for devices...
Connecting to device <MuxDevice: ID 2 ProdID 0x12ab Serial '670e5e2ce669cf4a1349266914718715085b3273' Location 0x14100000>
Connection established, relaying data
Connection closed
Done!

**Comment by flymedllva** [comment]
Hey.
This problem has nothing to do with this software. The software simply connects to your iPhone and removes the lock screen.

**Comment by acherevko1** [comment]
@FlymeDllVa I have the same problem. If I turn the phone on and off it recovers - so not a big deal, but the bypass still doesn't  work :( Iphone 6, iOS 12.4.8

**Comment by jamestangeres** [comment]
@skepzz @FlymeDllVa , did you fix your issue?

I got home button not working also after doing this line of code

command = "cd /;mount -o rw,union,update /;cd /Applications;mv Setup.app Setup.app.bak;uicache -a;" \
              "killall -9 SpringBoard"

**Comment by Saint-Dave-Cloud** [comment]
did you guys manage to get a fix for the home button?

**Comment by jamestangeres** [comment]
> did you guys manage to get a fix for the home button?

Yes, just reflash your iPhone to its compatible firmware. Use 3utools to download its firmware.
